name: "[Check] go validation"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  validate-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v3.2.0
      with:
        version: v1.49.0
    - name: Version check
      run: diff -u VERSION <(grep "var version = " trezord.go | cut -f 2 -d '"')
